config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "teams#index"

  resources :teams, only: [:index, :new, :show, :create] do
    member do
      post :join
      post :quit
      get :all_members
    end
    resources :projects, only: [:show, :new, :create] do
      member do
        post :join
        post :quit
        get :all_members
      end
      resources :todos do
        member do
          post :run
          post :pause
          post :finish
          post :delete
          post :reopen
          post :recover
        end
        resources :comments, only: [:new, :create]
      end
    end
  end
end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id          :integer          not null, primary key
#  name        :string
#  user_id     :integer
#  team_id     :integer
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Project < ApplicationRecord
  validates :name, presence: true
  belongs_to :team
  belongs_to :user
  has_many :todos

  has_many :project_relationships
  has_many :project_members, through: :project_relationships, source: :user
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_team_id
  before_action :require_is_project_member, only: [:show, :all_members]

  def show
    @project = @team.projects.find(params[:id])
    @todos = @project.todos.all
  end

  def new
    @project = Project.new
  end

  def create
    @project = @team.projects.new(project_params)
    @project.user = current_user
    if @project.save
      flash[:notice] = "成功创建项目"
      redirect_to team_path(@team)
    else
      render :new
    end
  end

  def join
    @project = @team.projects.find(params[:id])

    if !current_user.is_member_of_project?(@project)
      current_user.join_project!(@project)
      flash[:notice] = "成功加入项目"
    else
      flash[:notice] = "你已经是项目成员"
    end

    redirect_to :back
  end

  def quit
    @project = @team.projects.find(params[:id])

    if current_user.is_member_of_project?(@project)
      current_user.quit_project!(@project)
      flash[:notice] = "已退出该项目"
    else
      flash[:notice] = "不是成员，无法退出"
    end

    redirect_to :back
  end

  def all_members
    @project = @team.projects.find(params[:id])
    @members = @project.project_members.all
  end

  protected

  def find_team_id
    @team = Team.find(params[:team_id])
  end

  def require_is_project_member
    if !current_user.is_member_of_project?(Project.find(params[:id]))
      redirect_to root_path
      flash[:notice] = "暂无权限"
    end
  end

  private

  def project_params
    params.require(:project).permit(:name)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def render_project_member_or_not(user, project)
    if current_user && user.is_member_of_project?(project)
      content_tag(:span, "项目成员", class:"label label-success pull-right")
    else
      content_tag(:span, "不是项目成员", class:"label label-warning pull-right")
    end
  end

  def render_join_or_quit_project(user, team, project)
    if current_user && user.is_member_of_project?(project)
      link_to "退出项目", quit_team_project_path(team, project), method: :post, class:"btn btn-xs btn-default"
    else
      link_to "加入项目", join_team_project_path(team, project), method: :post, class:"btn btn-xs btn-default"
    end
  end

  def render_all_project_members(user, team, project)
    if current_user && user.is_member_of_project?(project)
      link_to "所有成员", all_members_team_project_path(team, project), class:"btn btn-xs btn-primary pull-right"
    end
  end
end

app/views/projects/_form.html.erb
<%= simple_form_for [@team, @project] do |f| %>
  <div class="form-group">
    <%= f.input :name, label: "项目名称", input_html: { class: "form-control" } %>
  </div>
  <%= f.submit "新建项目", class: "btn btn-primary pull-right", data: { disable_with: "创建中..." } %>
<% end %>

app/views/projects/all_members.html.erb
<div class="text-center">
  <h1><%= @project.name %></h1>
</div>

<div class="container">
    <div class="row col-md-6 col-md-offset-2 custyle">
    <table class="table table-striped custab">
    <thead>
        <tr>
          <th>项目成员</th>
        </tr>
    </thead>
        <% @members.each do |member| %>
        <tr>
          <td><%= member.email %></td>
        </tr>
        <% end %>
    </table>
    </div>
</div>

app/views/projects/new.html.erb
<div class="col-md-4 col-md-offset-4">
  <h2>新建项目</h2>
  <hr>

  <%= render "form" %>
</div>

app/views/projects/show.html.erb
<div class="text-center">
  <h1><%= @project.name %></h1>
</div>

<div class="container">
    <div class="row col-md-12">
    <table class="table table-striped custab">
    <thead>
      <%= link_to("新建任务", new_team_project_todo_path(@team, @project), class:"btn btn-primary btn-xs pull-right") %>
      <%= render_all_project_members(current_user, @team, @project) %>
        <tr>
            <th>任务名称</th>
            <th>任务描述</th>
            <th>任务状态</th>
            <th>任务所有人</th>
            <th>截止日期</th>
            <th class="text-center"></th>
        </tr>
    </thead>
        <% @todos.each do |todo| %>
          <tr>
            <th><%= link_to(todo.title, team_project_todo_path(@team, @project, todo)) %></th>
            <th><%= todo.description %></th>
            <th><%= render_todo_state(todo) %></th>
            <th><%= render_todo_assignee(todo) %></th>
            <th><%= render_todo_deadline(todo) %></th>
            <th>
              <% if current_user %>
                <%= render_todo_finish(@team, @project, todo) %>
                <%= render_todo_reopen(@team, @project, todo) %>
                <%= render_todo_comment(@team, @project, todo) %>
                <%= render_todo_delete(@team, @project, todo) %>
                <%= render_todo_edit(@team, @project, todo) %>
                <%= render_todo_run(@team, @project, todo) %>
                <%= render_todo_pause(@team, @project, todo) %>
                <%= render_todo_recover(@team, @project, todo) %>
              <% end %>
            </th>
          </tr>
        <% end %>
    </table>
    </div>
</div>