config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "teams#index"

  resources :teams, only: [:index, :new, :show, :create] do
    member do
      post :join
      post :quit
      get :all_members
    end
    resources :projects, only: [:show, :new, :create] do
      member do
        post :join
        post :quit
        get :all_members
      end
      resources :todos do
        member do
          post :run
          post :pause
          post :finish
          post :delete
          post :reopen
          post :recover
        end
        resources :comments, only: [:new, :create]
      end
    end
  end
end

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">x</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer id="footer" class="site-footer col-md-12 col-md-offset-0">
  <div class="copyright-info" style="text-align:center;">
    <span>©2017 Tower, Inc. All Rights Reserved</span>
  </div>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle"
              data-toggle="collapse"
              data-target=".navbar-ex1-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"> Tower
            </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-ex1-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav navbar-left">
                <%#= params.inspect %>
                <li> <%#= link_to("团队", "/") %> </li>
                <%# if params[:controller] == "projects" or params[:controller] == "events" or params[:id].present? %>
                  <li> <%#= link_to("项目", team_path(@team)) %> </li>
                  <li><%#= link_to("动态", team_events_path(@team)) %> </li>

                <%# end %>
              </ul>

              <ul class="nav navbar-nav navbar-right">
                <% if !current_user %>
                <li><%= link_to("注册", new_user_registration_path) %>
                </li>
                <li><%= link_to("登录", new_user_session_path) %></li>
            <% else %>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Hi! <%= current_user.email %>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <%#= link_to("团队列表", teams_path) %>
                        </li>
                        <li>
                            <%= link_to("退出", destroy_user_session_path, method: :delete) %>
                        </li>
                    </ul>
                </li>
                <% end %>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>